WEATHER_STACK_API_KEY = 'eacba2a5b47df58f521f91fc7986c7f4'
MAPBOX_API_KEY = 'pk.eyJ1IjoicHJhc2F0aGR2IiwiYSI6ImNrZmlhNjFqcDAxOHoydHA3MjhhNXIxNWIifQ.J6BsU_EM7TVf_9gPkx5bPQ'

module.exports={
    WEATHER_STACK_API_KEY:WEATHER_STACK_API_KEY,
    MAPBOX_API_KEY:MAPBOX_API_KEY
}